default: styles/beachcity.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
mastodon-dark: styles/application.scss
beachcity-single: styles/beachcity-single.scss
mastodon-light-single: styles/mastodon-light-single.scss
mastodon-dark-single: styles/mastodon-dark-single.scss
